#!/bin/bash

VIVADO="C:\apps\Xilinx\Vivado\2024.2\bin\vivado.bat"

# SCRIPTS=./hdl/scripts
PROJECT=./video.xpr

# PROJ_SCRIPT=./make_zub1cg_sbc_base.tcl

# Clean up old files before building a new project
# Remove old journal and log files

if [ -f vivado.log ]; then
  rm vivado.*
fi

# Remove the existing Vivado project directory

# if [ -d pllx2_ex2 ]; then

#   rm -rf pllx2_ex2

# fi

# Clean the ip directory

# mv ip ip.bak

# mkdir ip

# cp ip.bak/*.xci* ip/

# rm -rf ip.bak

# cd $SCRIPTS

$VIVADO $PROJECT &
